spring:

  datasource:
    url: jdbc:mysql://localhost:33061/authorization
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  address: 127.0.0.1
  port: 8081

cxf:
  path: /