spring:
  datasource:
    url: jdbc:h2:file:./workflow/camunda-db

server:
  address: 127.0.0.1
  port: 8080

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    client:
      base-url: http://localhost:8080/engine-rest
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false
