
package ru.lab.apps.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServiceApps", targetNamespace = "https://apps.lab.ru", wsdlLocation = "http://localhost:8082/apps?wsdl")
public class WebServiceApps
    extends Service
{

    private static final URL WEBSERVICEAPPS_WSDL_LOCATION;
    private static final WebServiceException WEBSERVICEAPPS_EXCEPTION;
    private static final QName WEBSERVICEAPPS_QNAME = new QName("https://apps.lab.ru", "WebServiceApps");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/apps?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEAPPS_WSDL_LOCATION = url;
        WEBSERVICEAPPS_EXCEPTION = e;
    }

    public WebServiceApps() {
        super(__getWsdlLocation(), WEBSERVICEAPPS_QNAME);
    }

    public WebServiceApps(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEAPPS_QNAME, features);
    }

    public WebServiceApps(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEAPPS_QNAME);
    }

    public WebServiceApps(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEAPPS_QNAME, features);
    }

    public WebServiceApps(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceApps(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AppsService
     */
    @WebEndpoint(name = "AppsPort")
    public AppsService getAppsPort() {
        return super.getPort(new QName("https://apps.lab.ru", "AppsPort"), AppsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppsService
     */
    @WebEndpoint(name = "AppsPort")
    public AppsService getAppsPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://apps.lab.ru", "AppsPort"), AppsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEAPPS_EXCEPTION!= null) {
            throw WEBSERVICEAPPS_EXCEPTION;
        }
        return WEBSERVICEAPPS_WSDL_LOCATION;
    }

}
